spring:
  application:
    name: office-online
office-online:
  host:  http://192.168.200.40
  domain-server-host:  http://192.168.200.39
  referer: openschool.devp.eastedu.ltd
  jwt:
    expiresTime: 43200
logging:
  file:
    max-size: 10MB
    max-history: 30
  level: [debug]
server:
  max-http-header-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

swagger:
  exclude-path:
    - /error/**
    - /actuator/**
